/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteTaskModal: typeof import('./src/components/modals/DeleteTaskModal.vue')['default']
    DeveloperAvatars: typeof import('./src/components/ui/DeveloperAvatars.vue')['default']
    EditableDateCell: typeof import('./src/components/EditableDateCell.vue')['default']
    EditableInputCell: typeof import('./src/components/EditableInputCell.vue')['default']
    EditableSelectCell: typeof import('./src/components/EditableSelectCell.vue')['default']
    ErrorBoundary: typeof import('./src/components/ui/ErrorBoundary.vue')['default']
    Footer: typeof import('./src/components/ui/Footer.vue')['default']
    Kanban: typeof import('./src/components/views/Kanban.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    MainTable: typeof import('./src/components/views/MainTable.vue')['default']
    Navigation: typeof import('./src/components/ui/Navigation.vue')['default']
    NewTaskModal: typeof import('./src/components/modals/NewTaskModal.vue')['default']
    PersonFilterModal: typeof import('./src/components/modals/PersonFilterModal.vue')['default']
    SortModal: typeof import('./src/components/modals/SortModal.vue')['default']
    Toolbar: typeof import('./src/components/ui/Toolbar.vue')['default']
  }
}
