/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ColoredBadge: typeof import('./src/components/ColoredBadge.vue')['default']
    ColorLegend: typeof import('./src/components/ColorLegend.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DeleteConfirmModal: typeof import('./src/components/DeleteConfirmModal.vue')['default']
    DeleteTaskModal: typeof import('./src/components/DeleteTaskModal.vue')['default']
    DeveloperAvatars: typeof import('./src/components/DeveloperAvatars.vue')['default']
    EditableCell: typeof import('./src/components/EditableCell.vue')['default']
    EditableDateCell: typeof import('./src/components/EditableDateCell.vue')['default']
    EditableInputCell: typeof import('./src/components/EditableInputCell.vue')['default']
    EditableSelectCell: typeof import('./src/components/EditableSelectCell.vue')['default']
    Kanban: typeof import('./src/components/Kanban.vue')['default']
    MainTable: typeof import('./src/components/MainTable.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NewTaskModal: typeof import('./src/components/NewTaskModal.vue')['default']
    PersonFilterModal: typeof import('./src/components/PersonFilterModal.vue')['default']
    SortModal: typeof import('./src/components/SortModal.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
